{
	"version": 1649099306,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"camera-sheet0.png",
		"camerastart-sheet0.png",
		"cameraend-sheet0.png",
		"bg_0-sheet0.png",
		"char_01-sheet0.png",
		"char_01-sheet1.png",
		"sprite-sheet0.png",
		"sprite2-sheet0.png",
		"logo-sheet0.png",
		"mixkit-retro-game-notification-212.m4a",
		"mixkit-retro-game-notification-212.ogg",
		"itumenu player (wav).m4a",
		"itumenu player (wav).ogg",
		"into-the-night-20928 (online-audio-converter.com).m4a",
		"into-the-night-20928 (online-audio-converter.com).ogg",
		"itumenu narrador (wav).m4a",
		"itumenu narrador (wav).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}