{
	"version": 1650934127,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"camera-sheet0.png",
		"camerastart-sheet0.png",
		"cameraend-sheet0.png",
		"logo-sheet0.png",
		"char_1-sheet0.png",
		"inittype-sheet0.png",
		"initcta-sheet0.png",
		"pattern-sheet0.png",
		"particles.png",
		"vitoria-sheet0.png",
		"char_2-sheet0.png",
		"char_3-sheet0.png",
		"char_4-sheet0.png",
		"bauruzinho-sheet0.png",
		"texto-sheet0.png",
		"texto-sheet1.png",
		"sol-sheet0.png",
		"sol2-sheet0.png",
		"sol3-sheet0.png",
		"particles2.png",
		"vitoria1-sheet0.png",
		"vitoria2-sheet0.png",
		"vitoria3-sheet0.png",
		"vitoria4-sheet0.png",
		"vitoria5-sheet0.png",
		"vitoria6-sheet0.png",
		"8a10deabril-sheet0.png",
		"calltoaction-sheet0.png",
		"mixkit-retro-game-notification-212.m4a",
		"mixkit-retro-game-notification-212.ogg",
		"itumenu player (wav).m4a",
		"itumenu player (wav).ogg",
		"into-the-night-20928 (online-audio-converter.com).m4a",
		"into-the-night-20928 (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}